### ISSUE TITLE
check_flexlm patch to support lmstat in PATH and/or with -l cmd line switch

### ISSUE THREAD

**Issue by olahaye74** [nagios-plugins/nagios-plugins#118]
check_flexlm has several design flaw that this patch partially addresses (addresses points 2 to 4):
1/ it requires the PATH_TO_LMSTAT variable to be setup in util.pm while this file is nnot a config file. Thus each time the package is upgraded, the config get lost
2/ it doesn't support finding lmstat in PATH
3/ it doesn't support getting lmstat binary path from command line switchs
4/ usage is wrongly documented (needs the -F switch to provide the licence file PATH)
5/ LM_LICENCE_FILE variable not supported
6/ licence directory instead of licence path not supported.

The ticketing system won't let me submit the patch file, so it is available here:
http://olivier.lahaye1.free.fr/OSCAR/check_flexlm.patch

Best regards,

Olivier.

**Comment by jfrickson** [comment]
1. `PATH_TO_LMSTAT` is set during `./configure`, so any update to plugins should set it appropriately, not lose it.
2. `./configure` looks in `PATH` for `lmstat`
3. True, but it shouldn't be necessary
4. Fixed
5. Fixed
6. Not going to do that without a _**real**_ good reason

Fixed in 'maint' branch via commit https://github.com/nagios-plugins/nagios-plugins/commit/766d141780fb74228662dc8e999ec580d5bd7eb5

**Comment by olahaye74** [comment]
1. Doesn't work when installing from RPM or DEB (package built without lestât in path)
2. Doesn't work when installing from RPM or DEB (package built without lestât in path)
3. Absolutely necessary as 1 and 2 are not fixed!
6. License directory IS a feature of lmgrd, that's a good reason!
