### ISSUE TITLE
check_http - -b option not used if -S option is given

### ISSUE THREAD

**Issue by cdienger** [nagios-plugins/nagios-plugins#263]
Version 2.20.

Running the check_http through a proxy that requires basic authentication:

./check_http -I 192.168.4.32 -S -p 3128 -j CONNECT www.nagios.com -u www.nagios.com:443 -b nagios:welcome  -v

This results in a error:

3078547736:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:769:
SSL initialized

Looking at a packet capture, check_http does not send proxy creds in the initial request and ignores the proxy's 407 response requesting that check_http send basic credentials. Credentials will be sent if -S is not used.

**Comment by jfrickson** [comment]
I've done some research on this, but couldn't get it to work right. I'll be looking into it more.

**Comment by ggonzalez2** [comment]
Okay, easy fix, the code for the first header sending did not have the Proxy-Auth test and send.   Fixed.

**Comment by hedenface** [comment]
@ggonzalez2 Which commit is it fixed in?

**Comment by hedenface** [comment]
Fixed via #297 via commit https://github.com/nagios-plugins/nagios-plugins/commit/4440e1592a698cb4e681f583cdf6b8a431156d33 ala @ggonzalez2

**Comment by andral** [comment]
Am I correct that the newest release 2.2.1 does not include #297 ?

**Comment by hedenface** [comment]
@andral That's correct.

**Comment by batmanme** [comment]
Hi,

I'm checking this check_http version 2.3.1 but it still throws me "SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:769:". Do we have any update on this?


Thanks
