### ISSUE TITLE
check_icmp: checking multiple ips, min alive not working

### ISSUE THREAD

**Issue by log1-c** [nagios-plugins/nagios-plugins#404]
Hi,

I'm trying to monitor the reachability of two ip addresses at once with the check_icmp.
I'm calling the check like this:
check_icmp -H ip1 -H ip2 -m 1

What I expected was that the plugin now returns CRITICAL when both IPs are not reachable. This seems not to be the case.

Looking at the verbose output I found out that there is a difference between "target" and "host", but I can't figure out what the difference would be:
```
./check_icmp -H IP-1 -H IP-2 -m 1 -v
ttl set to 64
Setting alarm timeout to 10 seconds
packets: 5, targets: 2
target_interval: 0.000, pkt_interval 80.000
crit.rta: 500.000
max_completion_time: 6300.000
crit = {500000, 80%}, warn = {200000, 40%}
pkt_interval: 80000  target_interval: 0  retry_interval: 0
icmp_pkt_size: 76  timeout: 10
time_passed: 803325  final_wait: 5496675  max_completion_time: 6300000
Waiting for 5496675 micro-seconds (5496.675 msecs)
handle_random_icmp(0x7fff66776c30, 0x7fff66776ac0)
Packet is no response to a packet we sent
icmp_sent: 10  icmp_recv: 0  icmp_lost: 0
targets: 2  targets_alive: 2
OK -
IP-1: rta nan, lost 100%
 :: IP-2: rta nan, lost 100%|
IP-1pl=100%;40;80;0;100
IP-2pl=100%;40;80;0;100
targets: 2, targets_alive: 0, hosts_ok: 2, hosts_warn: 0, min_hosts_alive: 1
```

As you can see both IPs are not reachable and the plugin still returns "OK".

Am I missing something or is the check_icmp plugin not suitable for the use case?

Best regards

**Comment by log1-c** [comment]
Is this project dead?
At least the check_icmp from the monitoring-plugins package (on Ubuntu) works as intended, so there is a "workaround".

**Comment by sawolf** [comment]
Hi @log1-c, 

The project isn't dead. I've been working on it (among other things) for a couple months, mostly working on more recent issues since they're the most likely to respond/help with reproducing bugs. 

As for your problem, I'll take a look at it today and let you know what I can find.

**Comment by sawolf** [comment]
I was able to reproduce your issue from the `maint` branch, so I didn't test anything from `master`.

For your exact use case, you may not need the `-m` argument. By default, the plugin will alert when both systems are unreachable. That said, I'm not sure how it'd handle high latency or high packet loss  for reachable hosts, so maybe not what you want.

I also created #487 which should fix the -m option (that is, it did in my own testing). Try compiling from there and let me know how this works for you.

**Comment by log1-c** [comment]
Hi @sawolf,

thanks for the update! And sorry for the "project dead" question. 
Didn't want to lessen your work.
Allow me one more (dumb) question: Does this project/the check plugins end up in the nagios-plugins* packages on e.g CentOS? Because I never compiled these manually :)

**Comment by sni** [comment]
Yes, this project ends up in the centos nagios-plugins package. Debian/Ubuntu,Gentoo,FreeBSD  use the monitoring-plugins as source.

**Comment by sawolf** [comment]
No worries :). And yes, Sven's comment is accurate.

**Comment by log1-c** [comment]
I just had a run in with this problem again.
Using `check_icmp v2.3.1.2.g19d0.dirty (nagios-plugins 2.3.1)` it seems like this is not fixed yet.
```
./check_icmp 8.8.8.8 9.9.9.9 12.3.4.5 -m 1 -v
address_family: 2 (IPv4 = 2; IPv6 = 10)
ttl set to 64
Setting alarm timeout to 10 seconds
packets: 5, targets: 3
target_interval: 0.000, pkt_interval 80.000
crit.rta: 500.000
max_completion_time: 9200.000
crit = {500000, 80%}, warn = {200000, 40%}
pkt_interval: 80000  target_interval: 0  retry_interval: 0
icmp_pkt_size: 76  timeout: 10
10.180 ms rtt from 8.8.8.8, outgoing ttl: 64, incoming ttl: 56, max: 10.180, min: 10.180
36.889 ms rtt from 9.9.9.9, outgoing ttl: 64, incoming ttl: 56, max: 36.889, min: 36.889
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
10.134 ms rtt from 8.8.8.8, outgoing ttl: 64, incoming ttl: 56, max: 10.180, min: 10.134
36.850 ms rtt from 9.9.9.9, outgoing ttl: 64, incoming ttl: 56, max: 36.889, min: 36.850
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
10.113 ms rtt from 8.8.8.8, outgoing ttl: 64, incoming ttl: 56, max: 10.180, min: 10.113
36.784 ms rtt from 9.9.9.9, outgoing ttl: 64, incoming ttl: 56, max: 36.889, min: 36.784
10.215 ms rtt from 8.8.8.8, outgoing ttl: 64, incoming ttl: 56, max: 10.215, min: 10.113
36.846 ms rtt from 9.9.9.9, outgoing ttl: 64, incoming ttl: 56, max: 36.889, min: 36.784
10.230 ms rtt from 8.8.8.8, outgoing ttl: 64, incoming ttl: 56, max: 10.230, min: 10.113
36.993 ms rtt from 9.9.9.9, outgoing ttl: 64, incoming ttl: 56, max: 36.993, min: 36.784
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
time_passed: 1351351  final_wait: 7848649  max_completion_time: 9200000
Waiting for 7848649 micro-seconds (7848.649 msecs)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
handle_random_icmp(0x7fff9865d220, 0x7fff9865d120)
icmp_sent: 15  icmp_recv: 10  icmp_lost: 0
targets: 3  targets_alive: 3
CRITICAL -
8.8.8.8
 :: 9.9.9.9
 :: 12.3.4.5: rta nan, lost 100%|
8.8.8.8rta=10.174ms;200.000;500.000;0; 8.8.8.8pl=0%;40;80;0;100 8.8.8.8rtmax=10.230ms;;;; 8.8.8.8rtmin=10.113ms;;;;
9.9.9.9rta=36.872ms;200.000;500.000;0; 9.9.9.9pl=0%;40;80;0;100 9.9.9.9rtmax=36.993ms;;;; 9.9.9.9rtmin=36.784ms;;;;
12.3.4.5rta=0.000ms;200.000;500.000;0; 12.3.4.5pl=100%;40;80;0;100 12.3.4.5rtmax=0.000ms;;;; 12.3.4.5rtmin=0.000ms;;;;
targets: 3, targets_alive: 2, hosts_ok: 0, hosts_warn: 0, min_hosts_alive: 1

```
