### ISSUE TITLE
check_smtp broken when using -S or -s and -D

### ISSUE THREAD

**Issue by Helmut1972** [nagios-plugins/nagios-plugins#651]
Before 2.4.0 I used

`-S -D 14`

to check certificate vailidity:

```
[helmut@BSDHelmut ~]$ sudo /usr/local/libexec/nagios/check_smtp -H 192.168.124.35 -t 30 -p 25 -S -D 14
SSL OK - Certificate '*.mydomain' will expire in 233 days on 2022-12-09 15:12 +0100/CET.
[helmut@BSDHelmut ~]$ pkg info -ix nagios-plugins
nagios-plugins-2.3.3_2,1
[helmut@BSDHelmut ~]$
```

With 2.4.0 -S or -s do not work together with -D anymore:

```
[helmut@BSDHelmut ~]$ sudo /usr/local/libexec/nagios/check_smtp -H 192.168.124.35 -t 30 -p 25 -S
SMTP OK - 0.042 sec. response time|time=0.042408s;;;0.000000
[helmut@BSDHelmut ~]$ sudo /usr/local/libexec/nagios/check_smtp -H 192.168.124.35 -t 30 -p 25 -S -D 14
check_smtp: Set either -s/--ssl or -S/--starttls
Usage:
check_smtp -H host [-p port] [-4|-6] [-e expect] [-C command] [-R response] [-f from addr]
[-A authtype -U authuser -P authpass] [-w warn] [-c crit] [-t timeout] [-q]
[-F fqdn] [-S] [-L] [-D warn days cert expire[,crit days cert expire]] [--sni] [-v]
$[helmut@BSDHelmut ~]$ pkg info -ix nagios-plugins
nagios-plugins-2.4.0,1
[helmut@BSDHelmut ~]$ uname -rs
FreeBSD 13.0-RELEASE-p10
[helmut@BSDHelmut ~]$
```

**Comment by sawolf** [comment]
Should be fixed by #649 if you want to try that patch - otherwise, there should be a bugfix release out sometime soon.

**Comment by Helmut1972** [comment]
Works, thank you!

**Comment by fabianwenk** [comment]
As this patch was also added for the FreeBSD Port, I did setup this check for STARTTLS (-S / --starttls), which works, but it still (or now also) fails with SSL (-s / --ssl).

STARTTLS (works):
```
superman:/usr/local/libexec/nagios # ./check_smtp --starttls -H 192.0.2.2 -p 25 --certificate=21,14
SSL OK - Certificate 'example.com' will expire in 27 days on 2022-10-07 03:38 +0200/CEST.
```
SSL (fails, aka does check TCP port but not the certificate):
```
superman:/usr/local/libexec/nagios # ./check_smtp --ssl -H 192.0.2.2 -p 465 --certificate=21,14
SMTP OK - 0.223 sec. response time|time=0.222638s;;;0.000000
```

**Comment by Herbert-Hotz** [comment]
Same (-D -S) here on Fedora 36. Bug is not resolved (hostname changed):

**check_smtp!-H xyz.domain.tld -S -D 30,14**

**Comment by sawolf** [comment]
Based on this thread, it's not clear to me whether people are still seeing errors after the two pull requests (which are now merged), or if they're confirming that they're still seeing issues (understandable, since it's been a long time since 2.4.0 came out).

If either of you (or any other readers) are still having issues with this after compiling from `master`, please let me know. If I don't hear anything, I'm going to assume that things are fine and we'll release 2.4.1 early next week.

**Comment by Helmut1972** [comment]
> If either of you (or any other readers) are still having issues with this after compiling from `master`, please let me know. If I don't hear anything, I'm going to assume that things are fine and we'll release 2.4.1 early next week.

2.4.1 works for me.
